sudo: required
dist: trusty

env:
  global:
  # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
  #   via the "travis encrypt" command using the project repo's public key
   - secure: "IBtZYZfuT3Ho1fM+7Mq0xKwuds8BGvL+PuT4Ly22N2Rij0PeJEy+qK1AXj6toSs6Hku6FhsJJCJZ4LZ0aokTabVPV6GqigaVq7iusSFwOTiW0CiyIuZmLHhDy7ZsqOTFOBgc0z7z73wygZPuSWcXVYlzWjpa15GMr3X0qE3nFLdIzGz3iLye/sZG81cE7/Fjpd9pAjYGo86ocavyJGi5CcSJFqcJOJhuPulbWbxFHtShmnoshckQL5ghH8eXuBr0tsBMR6fCAoWxZ8s7gDXyIhnifnoUp5C/jSCuQ+wUh0Qh6WJlWWE6+Oh6d4++zfCexejo/DEXFVHZaQMIcZQ7Wq8h9oVvSHA/6sVmpvCKKnbGG8IEQXxJrbarZdBszZSyZxyC4tF9uFax7W644RzB3kxcV52IkLV2VC1sTnzvYph0Tz6ISmyYPJekLDYohmWkm9E0BGVGaXHtaEc1S0+IbhJ5IqoK2brcVHXJvnde8qDyvE67AyLqC0PI62+nOJ35Bvkt9yDIVPi5+XLFWEXejfjuqhXNVpaKoMGiuCWazLe6X1cCYj3kq0pVaweW/rTf+pBycKynCeeBnXlHk8WJdVtE5HDdhW4AQM7s+BQX8yfOd+AfpOjVRbRTVsASuwd3ViabB83fk5foh6QIHvdLTj0eoR55L2oNInAnASZTWbY="

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

language: c

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get install automake autoconf libtool build-essential git-core
  - pushd . && cd $HOME
  - git clone https://github.com/eladraz/xStl
  - export XSTL_PATH=`pwd`/xStl
  - cd xStl
  - ./build.sh
  - popd

script: ./build.sh

addons:
  coverity_scan:
    project:
      name: "eladraz/dismount"
      description: "dismount builds from Travis-CI"
    notification_email: e@eladraz.com
    build_command_prepend: "./autogen.sh && ./configure --prefix=${PWD}/out --enable-debug --enable-unicode --with-xstl=${XSTL_PATH}"
    build_command:  "make -j 4"
    branch_pattern: master
